### ISSUE TITLE
luna-devel fails with could not find group pulp

### ISSUE THREAD

**Issue by ares** [theforeman/forklift#1079]
the first error coming from the installer, this may be a bug in the puppet module itself, I can't debug further at this moment

```
  [ERROR 2019-12-29T14:32:55 verbose]  Could not find group pulp
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type/file/group.rb:26:in `block in insync?'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type/file/group.rb:25:in `map!'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type/file/group.rb:25:in `insync?'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/property.rb:276:in `safe_insync?'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:125:in `sync_if_needed'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:90:in `block in perform_changes'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:89:in `each'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:89:in `perform_changes'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:21:in `evaluate'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:263:in `apply'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:283:in `eval_resource'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:187:in `call'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:187:in `block (2 levels) in evaluate'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:521:in `block in thinmark'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:520:in `thinmark'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:187:in `block in evaluate'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/graph/relationship_graph.rb:122:in `traverse'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:174:in `evaluate'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:240:in `block (2 levels) in apply'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:521:in `block in thinmark'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:520:in `thinmark'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:239:in `block in apply'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/log.rb:161:in `with_destination'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/report.rb:146:in `as_logging_destination'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:238:in `apply'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:194:in `block (2 levels) in apply_catalog'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:521:in `block in thinmark'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:520:in `thinmark'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:193:in `block in apply_catalog'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:233:in `block in benchmark'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:232:in `benchmark'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:192:in `apply_catalog'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:381:in `run_internal'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:242:in `block in run'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:274:in `override'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:219:in `run'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:343:in `apply_catalog'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:260:in `block (2 levels) in main'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:274:in `override'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:243:in `block in main'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:274:in `override'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:207:in `main'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:177:in `run_command'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:382:in `block in run'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:687:in `exit_on_fail'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:382:in `run'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:143:in `run'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:77:in `execute'
    [ERROR 2019-12-29T14:32:55 verbose] /opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
    [ERROR 2019-12-29T14:32:55 verbose]  /Stage[main]/Certs::Qpid_client/File[/etc/pki/pulp]/group: change from 'root' to 'pulp' failed: Could not find group pulp
    [ WARN 2019-12-29T14:32:55 verbose]  /File[/etc/pki/pulp]/seluser: seluser changed 'unconfined_u' to 'system_u'
    [ WARN 2019-12-29T14:32:55 verbose]  /Stage[main]/Certs::Qpid_client/File[/etc/pki/pulp/qpid]: Dependency File[/etc/pki/pulp] has failures: true
    [ WARN 2019-12-29T14:32:55 verbose]  /Stage[main]/Certs::Qpid_client/File[/etc/pki/pulp/qpid]: Skipping because of failed dependencies
    [ WARN 2019-12-29T14:32:55 verbose]  /Stage[main]/Certs::Qpid_client/Cert[luna-devel.example.tst-qpid-client-cert]: Skipping because of failed dependencies
    [ WARN 2019-12-29T14:32:55 verbose]  /Stage[main]/Certs::Qpid_client/Key_bundle[/etc/pki/pulp/qpid/client.crt]: Skipping because of failed dependencies
    [ WARN 2019-12-29T14:32:55 verbose]  /Stage[main]/Certs::Qpid_client/File[/etc/pki/pulp/qpid/client.crt]: Skipping because of failed dependencies
    [ WARN 2019-12-29T14:32:55 verbose]  /Stage[main]/Certs::Qpid_client/Pubkey[/etc/pki/pulp/qpid/ca.crt]: Skipping because of failed dependencies
```

a simple workaround

```
groupadd pulp
```

**Comment by ekohl** [comment]
This should be fixed.
