### ISSUE TITLE
Fedora 34 support

### ISSUE THREAD

**Issue by fao89** [theforeman/forklift#1362]
After upgrading to fedora34, I get this error:
```
pulp_installer on  master [⇡$] via 🐍 v3.9.1 (venv) 
❯ vagrant up pulp3-source-fedora33     
/usr/share/vagrant/gems/gems/vagrant-2.2.9/plugins/kernel_v2/config/vm.rb:341:in `provision': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /home/faguiar/project/pulp_installer/forklift/vagrant/lib/forklift/box_distributor.rb:188:in `block in configure_ansible'
	from /home/faguiar/project/pulp_installer/forklift/vagrant/lib/forklift/box_distributor.rb:186:in `each'
	from /home/faguiar/project/pulp_installer/forklift/vagrant/lib/forklift/box_distributor.rb:186:in `each_with_index'
	from /home/faguiar/project/pulp_installer/forklift/vagrant/lib/forklift/box_distributor.rb:186:in `configure_ansible'
	from /home/faguiar/project/pulp_installer/forklift/vagrant/lib/forklift/box_distributor.rb:90:in `block in define_vm'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/config/loader.rb:126:in `block (2 levels) in load'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/config/loader.rb:119:in `each'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/config/loader.rb:119:in `block in load'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/config/loader.rb:116:in `each'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/config/loader.rb:116:in `load'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/vagrantfile.rb:173:in `machine_config'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/environment.rb:958:in `block in find_configured_plugins'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/environment.rb:956:in `each'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/environment.rb:956:in `find_configured_plugins'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/environment.rb:983:in `process_configured_plugins'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/environment.rb:178:in `initialize'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.9/bin/vagrant:168:in `new'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.9/bin/vagrant:168:in `<top (required)>'
	from /usr/share/vagrant/gems/bin/vagrant:23:in `load'
	from /usr/share/vagrant/gems/bin/vagrant:23:in `<main>'
```

**Comment by evgeni** [comment]
Are you running a version that has https://github.com/theforeman/forklift/pull/1353 included?

**Comment by fao89** [comment]
I was not, pulp_installer is using an outdated forklift, 
thank you!
I'll update pulp_installer
