### ISSUE TITLE
Failing forklift - foreman_installer: Run installer failed

### ISSUE THREAD

**Issue by junezhang** [theforeman/forklift#448]
HI, When running the forklift installation, I met the below error message. 
CentOS 7, Vagrant 1.9.4, Vagrant-libvirt: 0.0.37, ansible: 2.3.0.0

```
cmd: foreman-installer -v --scenario "katello-devel"  --disable-system-checks --katello-devel-github-username junezhang

start: 2017-05-08 09:45:34.393983

end: 2017-05-08 09:45:35.570904

delta: 0:00:01.176921

stderr: /usr/share/gems/gems/kafo-2.0.1/lib/kafo/puppet_module.rb:69:in `parse': No Puppet module parser is installed and no cache of the file /usr/share/katello-installer-base/modules/katello_devel/manifests/init.pp is available. Please check debug logs and install optional dependencies for the parser. (Kafo::ParserError)
	from /usr/share/gems/gems/kafo-2.0.1/lib/kafo/configuration.rb:97:in `block in modules'
	from /usr/share/gems/gems/kafo-2.0.1/lib/kafo/configuration.rb:97:in `map'
	from /usr/share/gems/gems/kafo-2.0.1/lib/kafo/configuration.rb:97:in `modules'
	from /usr/share/gems/gems/kafo-2.0.1/lib/kafo/configuration.rb:207:in `params'
	from /usr/share/gems/gems/kafo-2.0.1/lib/kafo/configuration.rb:217:in `preset_defaults_from_puppet'
	from /usr/share/gems/gems/kafo-2.0.1/lib/kafo/kafo_configure.rb:285:in `set_parameters'
	from /usr/share/gems/gems/kafo-2.0.1/lib/kafo/kafo_configure.rb:100:in `initialize'
	from /usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `new'
	from /usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
	from /usr/share/gems/gems/kafo-2.0.1/lib/kafo/kafo_configure.rb:163:in `run'
	from /sbin/foreman-installer:8:in `<main>'
	to retry, use: --limit @/home/junezhang/.ansible/retry-files/devel.retry

PLAY RECAP *********************************************************************
centos7-devel              : ok=10   changed=9    unreachable=0    failed=1
```

The full log is here: https://gist.github.com/junezhang/940c2098f4dd96385af058ed34f38beb 

Any ideas? Thanks.

**Comment by ekohl** [comment]
I suspect this is due to http://ci.theforeman.org/job/release_build_katello_installer/638/console. https://github.com/Katello/puppet-katello/pull/189 might help with this.

**Comment by ekohl** [comment]
The nightlies are building again and I'm able to install again so I'm going to assume this is fixed. Please re-open if the problem persists.
