### ISSUE TITLE
pulplift now breaks with error with recent change to forklift

### ISSUE THREAD

**Issue by bmbouter** [theforeman/forklift#913]
If I have github.com/pulp/pulplift/ at HEAD and forklift at the most recent HEAD also, then `vagrant up pulp3-source-fedora28` you will get an error like this:

```
==> pulp3-source-fedora28: Running provisioner: main0 (ansible)...
#<Thread:0x00005571f23f4120@/usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:71 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	53: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	52: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `action'
	51: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `call'
	50: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/environment.rb:592:in `lock'
	49: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:202:in `block in action'
	48: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:227:in `action_raw'
	47: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	46: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	45: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	44: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	43: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	42: from /usr/share/vagrant/gems/gems/vagrant-sshfs-1.3.1/lib/vagrant-sshfs/action_hostpath_fixup.rb:102:in `call'
	41: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	40: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	39: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	38: from /usr/share/vagrant/gems/gems/vagrant-sshfs-1.3.1/lib/vagrant-sshfs/action_hostpath_fixup.rb:125:in `call'
	37: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	36: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	35: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	34: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	33: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	32: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	31: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	30: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	29: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	28: from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	27: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	26: from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/handle_storage_pool.rb:52:in `call'
	25: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	24: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	23: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	22: from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/handle_box_image.rb:113:in `call'
	21: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	20: from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/create_domain_volume.rb:82:in `call'
	19: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	18: from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/create_domain.rb:308:in `call'
	17: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	16: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:103:in `call'
	15: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:103:in `each'
	14: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:126:in `block in call'
	13: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:126:in `call'
	12: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/environment.rb:504:in `hook'
	11: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	10: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	 9: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 8: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 7: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 6: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 5: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `call'
	 4: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:138:in `run_provisioner'
	 3: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/plugins/provisioners/ansible/provisioner/host.rb:23:in `provision'
	 2: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/plugins/provisioners/ansible/provisioner/base.rb:100:in `check_files_existence'
	 1: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/plugins/provisioners/ansible/provisioner/host.rb:338:in `check_path_is_a_file'
/usr/share/vagrant/gems/gems/vagrant-2.0.2/plugins/provisioners/ansible/provisioner/host.rb:329:in `check_path': `galaxy_role_file` does not exist on the host: /home/bmbouter/devel/pulp3/pulplift/requirements.yml (VagrantPlugins::Ansible::Errors::AnsibleError)
`galaxy_role_file` does not exist on the host: /home/bmbouter/devel/pulp3/pulplift/requirements.yml
```

If I revert my forklift checkout to 188dcc5e343b087efffcf3b9392d3fdf0ab89882 then it works just fine. Does pulplift need a change, or is a change needed for forklift?

**Comment by mdellweg** [comment]
This sounds a lot like the change, i initiated (https://github.com/theforeman/forklift/pull/908).
The fix needs to be in pulplift, and is contained in https://github.com/pulp/pulplift/pull/3.
The path to the galaxy-file in pulplift is wrong ATM.

**Comment by bmbouter** [comment]
Thanks! I will close this and we can resolve it through pulp/pulplift#3
